[package]
name = "gpu_compute_test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
wgpu = "28.0"
bytemuck = { version = "1.24", features = ["derive"] }
futures-intrusive = "0.5"
num_cpus = "1.17"
rand = "0.9.2"
